config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  delete 'posts/:id', to: 'posts#destroy'
  resources :posts
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :contents, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all.order(created_at: 'desc')
    end
    
    def show
        @post = Post.find(params[:id])
    end
    
    def new
        @post = Post.new
    end
    
    def create
        @post = Post.new(post_params)
        if @post.save
            
            redirect_to posts_path
        else
            render 'new'
        end
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to posts_path
        else
            render 'edit'
        end
    end 
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end
    
    private
      def post_params
        params.require(:post).permit(:title, :contents)
      end
      
end

app/helpers/application_helper.rb
module ApplicationHelper
    def date_format(datetime)
        time_ago_in_words(datetime) + '前'
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <meta charset="utf-8" />
    <link rel="stylesheet" href="application.css" type="text/css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">

        <%= yield %>
      </div>

</body>
</html>

app/views/posts/edit.html.erb
<h2>編集</h2>
<%= form_for @post, url: post_path(@post) do |f| %>
<p>
    <%= f.text_field :title %>
</p>
<p>
    <%= f.text_area :contents %>
</p>
<p>
    <%= f.submit %>
</p>
<% end %>

app/views/posts/index.html.erb
<!DOCTYPE HTML>
<html lang="ja">
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="/app/stylesheets/style.css">
</head>

<body>
    <div id="wrap">
        <div id="left_content">
            <h3>近畿大学</h3>
            <h4>近畿大学総務部広報室のTwitter公式アカウントです。近畿大学ホームページの更新情報を中心に、大学に関する情報を発信していきます。個別のお問い合わせには返信を行っておりませんので、ご了承ください。</h4>
<h3>
    <%= link_to 'ツイート', new_post_path %>
</h3>
        </div>
        <div id="right_content">
       
          <ul>
    <% @posts.each do |post| %>
    <li>
        <tr>
        <h3>
            近畿大学
        <time datetime="<%= post.created_at %>">
            <%= time_ago_in_words(post.created_at) %>
　　　　</time>
　　　　</h3>
         
        <td><%= post.contents %></td>
       
　　　　</tr>
        <%= link_to '[編集]', edit_post_path(post) %>
        <%= link_to '[削除]', post_path(post), method: :delete, data: { confirm: '本当に削除してもいいですか？'} %>
    </li>
    <% end %>
</ul>
        </div>
    </div>
 

app/views/posts/new.html.erb
<h2>新規投稿</h2>
<%= form_for :post, url: posts_path do |f| %>
<p>
    <%= f.text_field :title %>
</p>
<p>
    <%= f.text_area :contents %>
</p>
<p>
    <%= f.submit "投稿" %>
</p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.contents %></p>